import Head from "next/head";
import { useState } from "react";
import {
  Container,
  Box,
  Button,
  Typography,
  InputLabel,
  Select,
  MenuItem,
  FormControl,
} from "@mui/material";
import { TodoCard } from "@/components/TodoCard";
import { Header } from "@/components/Header";
import { useGetTodosQuery } from "@/features/todos/todosApi";
import { useThemeContext } from "@/contexts/ThemeContext";
import { ToastContainer, Bounce } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Home() {
  const { mode } = useThemeContext();
  const { data: todos, isLoading, error } = useGetTodosQuery();
  const [time, setTime] = useState("");

  return (
    <>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Typography
          variant="h3"
          sx={{
            margin: 2,
            textAlign: "center",
            fontWeight: 700,
          }}
        >
          TODO LIST
        </Typography>
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            width: "100%",
            padding: 2,
          }}
        >
          <Button variant="contained" size="large" color="secondary">
            Add Task
          </Button>
          <FormControl sx={{ minWidth: 160 }}>
            <InputLabel id="time-select-label">Time</InputLabel>
            <Select
              labelId="time-select-label"
              value={time}
              label="Time"
              onChange={(e) => setTime(e.target.value)}
            >
              <MenuItem value="all">All</MenuItem>
              <MenuItem value="today">Today</MenuItem>
              <MenuItem value="last week">Last Week</MenuItem>
            </Select>
          </FormControl>
        </Box>
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            gap: 2,
          }}
        >
          {isLoading && <Typography>Loading todos...</Typography>}
          {todos && Array.isArray(todos) && todos.length > 0 ? (
            todos.map((todo) => <TodoCard key={todo.id} {...todo} />)
          ) : (
            <Typography>No todos found.</Typography>
          )}
        </Box>
      </Container>
      <ToastContainer
        position="bottom-right"
        autoClose={2000}
        closeOnClick
        theme={mode}
        transition={Bounce}
      />
    </>
  );
}
