import Head from "next/head";
import { useState, useEffect } from "react";
import { useSelector } from "react-redux";
import { selectSession } from "@/features/auth/authSlice";
import {
  Container,
  Box,
  Button,
  Typography,
  InputLabel,
  Select,
  MenuItem,
  FormControl,
} from "@mui/material";
import { TodoCard } from "@/components/TodoCard";
import { Header } from "@/components/Header";
import { createClient } from "@/utils/supabase/client";

export default function Home() {
  const [todos, setTodos] = useState([]);
  const [time, setTime] = useState("");
  const session = useSelector(selectSession);
  const supabase = createClient();

  useEffect(() => {}, []);

  return (
    <>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Typography
          variant="h3"
          sx={{
            margin: 2,
            textAlign: "center",
            fontWeight: 700,
          }}
        >
          TODO LIST
        </Typography>
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            width: "100%",
            padding: 2,
          }}
        >
          <Button variant="contained" size="large" color="secondary">
            Add Task
          </Button>
          <FormControl sx={{ minWidth: 160 }}>
            <InputLabel id="time-select-label">Time</InputLabel>
            <Select
              labelId="time-select-label"
              value={time}
              label="Time"
              onChange={(e) => setTime(e.target.value)}
            >
              <MenuItem value="all">All</MenuItem>
              <MenuItem value="today">Today</MenuItem>
              <MenuItem value="last week">Last Week</MenuItem>
            </Select>
          </FormControl>
        </Box>
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            gap: 2,
          }}
        >
          {/* HERE */}
          <TodoCard />
          <TodoCard />
        </Box>
      </Container>
    </>
  );
}
