name: My first workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-node@v4
        name: Set up Node.js
        with:
          node-version: "20"
          cache: "npm"

      - name: Cache Node Modules
        id: cache-npm # Give this step an ID to reference its output
        uses: actions/cache@v4 # Use the caching action
        with:
          path: ~/.npm # Cache npm's global cache directory
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }} # Unique key based on OS and package-lock.json
          restore-keys: | # Keys to try if the primary key doesn't match exactly
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci
        if: steps.cache-npm.outputs.cache-hit != 'true'

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist
